### ISSUE TITLE
How do Avatar is clickeable although IconButton is not working for Avatar

### ISSUE THREAD

**Issue by Chandracbs** [abrielequdsi/Whatsapp-Web-Clone#1]

**Comment by Yogeshraj** [comment]
IconButton will work for Avatar. Check this out

const dpChange = () =>{
    alert();
}

<IconButton onClick={dpChange}>
         <Avatar />
</IconButton>

**Comment by Yogeshraj** [comment]
IconButton will work for Avatar. Check this out

```javascript
const dpChange = () =>{
    alert();
}

<IconButton onClick={dpChange}>
         <Avatar />
</IconButton>
```
